name: 刷步数2

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  schedule:
    - cron: '12 9-10 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: 开始
        env:
          CONFIG: ${{ secrets.CONFIG2 }}
        run: |
          pip install --upgrade pip
          pip3 install requests
          python3 main.py
